"use client";

import { ArrowDown, ArrowUpRight, Brain, Check, CircleHelp, Dumbbell, MessageCircle, Moon, Salad, ShieldCheck, Sparkles, Stethoscope } from "lucide-react";

const updated = "24 August 2026";

function Header() {
  return <><div className="topline"><div className="container">An evidence-informed place to understand your body · Updated {updated}</div></div><header className="container nav"><a className="logo" href="#top"><span className="logo-mark" />cyclewise</a><nav className="nav-links"><a href="#learn">Learn</a><a href="#guidelines">Guidelines</a><a href="#care">Care</a><a href="#faq">FAQs</a><a href="#screener">Screener chatbot</a></nav><a className="nav-cta" href="/admin">Admin sign in</a></header></>;
}

export default function Home() {
  return <main id="top"><Header /><section className="hero"><div className="container hero-grid"><div><div className="eyebrow">A calmer guide to PCOS</div><h1>Understand your body, <em>in your own time.</em></h1><p className="hero-copy">Polycystic ovary syndrome can look different for everyone. Find clear, kind information to help you feel more informed and ready for your next conversation with a doctor.</p><div className="button-row"><a className="button button-primary" href="#learn">Start exploring <ArrowDown size={16} /></a><a className="button button-ghost" href="#guidelines">See latest guidelines <ArrowUpRight size={16} /></a></div><p className="hero-note">Always remember: you know your body best. A healthcare professional can help you make sense of symptoms.</p></div><div className="hero-art" aria-label="Abstract illustration of connected circles"><div className="art-ring" /><span className="art-caption">Small steps. Better questions. More support.</span></div></div></section>

<section className="section section-alt" id="learn"><div className="container"><div className="section-head"><div><div className="eyebrow">Start here</div><h2>The basics, made simple.</h2></div><p className="section-intro">PCOS is common, manageable, and never your fault. Begin with the pieces that feel most useful today.</p></div><div className="card-grid"><a className="card" href="#what"><div className="icon-tile"><Sparkles size={20} /></div><h3>What is PCOS?</h3><p>A common hormone condition that can affect periods, skin, hair, and how your body uses energy.</p><span className="source">Learn the basics →</span></a><a className="card" href="#symptoms"><div className="icon-tile"><Stethoscope size={20} /></div><h3>Symptoms & diagnosis</h3><p>What to look for, what to ask, and how clinicians usually work toward a diagnosis.</p><span className="source">Know the signs →</span></a><a className="card" href="#care"><div className="icon-tile"><ShieldCheck size={20} /></div><h3>Care that fits you</h3><p>Practical lifestyle ideas and an overview of treatment options, always with your doctor in the loop.</p><span className="source">Explore care →</span></a></div></div></section>

<section className="section screener-section" id="screener"><div className="container screener-panel"><div className="icon-tile"><MessageCircle size={20} /></div><div><div className="eyebrow">Need more support?</div><h2>Explore questions with our PCOS screener chatbot.</h2><p className="section-intro">For a quick check or related questions about PCOS, visit our dedicated screener website and chat with the bot. It is a separate resource from this educational guide.</p><a className="button button-primary" href="https://pcos-screener-bot-9sjn.onrender.com/" target="_blank" rel="noreferrer">Visit the PCOS screener chatbot <ArrowUpRight size={16} /></a></div></div></section>

<section className="section" id="what"><div className="container split"><div><div className="eyebrow">01 · What is PCOS?</div><h2>A real condition, with many faces.</h2><p className="section-intro">PCOS is a long-term health condition linked to hormones. Some people have irregular periods, higher levels of certain hormones, or ovaries that look different on a scan. You do not need every symptom to have PCOS.</p><div className="stat-row"><div className="stat"><strong>1 in 10</strong><span>people with ovaries may have PCOS</span></div><div className="stat"><strong>Many paths</strong><span>symptoms vary from person to person</span></div><div className="stat"><strong>Not your fault</strong><span>it is not caused by a lack of willpower</span></div></div></div><div className="list"><div className="list-item"><span className="number">01</span><div><strong>Hormones</strong><span>Hormones are chemical messengers. In PCOS, some may be out of balance.</span></div></div><div className="list-item"><span className="number">02</span><div><strong>Cycles</strong><span>Periods may come less often, be unpredictable, or sometimes stop.</span></div></div><div className="list-item"><span className="number">03</span><div><strong>Whole-body health</strong><span>PCOS can be connected with blood sugar, cholesterol, sleep, and mood.</span></div></div><div className="list-item"><span className="number">04</span><div><strong>Myth / fact</strong><span>PCOS does not mean you cannot get pregnant, and it is not defined by cysts alone.</span></div></div></div></div></section>

<section className="section section-alt" id="symptoms"><div className="container split"><div><div className="eyebrow">02 · Symptoms & diagnosis</div><h2>Questions are a good place to start.</h2><p className="section-intro">There is no single test for PCOS. A doctor will listen to your story, ask about your health, and may use blood tests or an ultrasound.</p></div><div className="card-grid" style={{gridTemplateColumns: "1fr 1fr"}}><div className="card"><div className="icon-tile"><CircleHelp size={20} /></div><h3>Common signs</h3><ul><li>Periods that are irregular or absent</li><li>Extra facial or body hair</li><li>Acne or oily skin</li><li>Hair thinning</li><li>Difficulty getting pregnant</li></ul></div><div className="card"><div className="icon-tile"><Check size={20} /></div><h3>What diagnosis may include</h3><ul><li>Your period and symptom history</li><li>A gentle physical check</li><li>Blood tests for hormones</li><li>Checking other possible causes</li><li>Sometimes an ultrasound</li></ul></div></div></div></section>

<section className="section" id="guidelines"><div className="container"><div className="section-head"><div><div className="eyebrow">03 · Reviewed regularly</div><h2>Latest guidelines, translated.</h2></div><p className="section-intro">Short summaries in everyday language. Each one links to the trusted source, and nothing is published without review.</p></div><div className="guideline"><span className="eyebrow">2023 international evidence-based guideline</span><h3>PCOS care should be personal, not one-size-fits-all.</h3><p>Experts recommend shared decision-making: your goals, preferences, symptoms, and overall health should shape your care. Lifestyle support is helpful for everyone, whatever their body size.</p><a className="source" href="https://www.monash.edu/medicine/mchri/pcos/guideline" target="_blank" rel="noreferrer">Read the source at Monash University <ArrowUpRight size={13} /></a></div><div className="guideline"><span className="eyebrow">2023 mental health recommendation</span><h3>Mood deserves a place in every PCOS conversation.</h3><p>Guidelines encourage clinicians to ask about depression and anxiety, and to offer support when needed. Seeking help is a sign of care, not a failure.</p><a className="source" href="https://www.monash.edu/medicine/mchri/pcos/guideline" target="_blank" rel="noreferrer">Read the source at Monash University <ArrowUpRight size={13} /></a></div><p className="hero-note">Last updated on {updated} · Next scheduled source check: 31 August 2026</p></div></section>

<section className="section section-alt" id="care"><div className="container"><div className="section-head"><div><div className="eyebrow">04 · Prevention & lifestyle</div><h2>Support your health gently.</h2></div><p className="section-intro">There is no perfect PCOS routine. Try small, repeatable changes and choose what feels realistic for your life.</p></div><div className="card-grid"><div className="card"><div className="icon-tile"><Salad size={20} /></div><h3>Eat regularly</h3><p>Build meals around foods you enjoy, including fibre, protein, and colourful plants. No single “PCOS diet” is required.</p></div><div className="card"><div className="icon-tile"><Dumbbell size={20} /></div><h3>Move your way</h3><p>Walking, dancing, stretching, or strength work can all support health. Choose movement you can return to.</p></div><div className="card"><div className="icon-tile"><Moon size={20} /></div><h3>Protect your rest</h3><p>A regular wind-down routine and support for sleep problems can make everyday symptoms easier to handle.</p></div></div><div className="split" style={{marginTop: "65px"}}><div><div className="eyebrow">Treatment overview</div><h2>Care has options.</h2></div><div><p className="section-intro">Treatment depends on what matters to you: period regularity, skin or hair symptoms, fertility, blood sugar, mood, or something else. A doctor can talk through options and possible benefits and risks. Never start or stop treatment without medical advice.</p><a className="button button-primary" href="#about">See sources & safety note <ArrowUpRight size={16} /></a></div></div></div></section>

<section className="section" id="mental"><div className="container split"><div><div className="eyebrow">05 · Mental health & PCOS</div><h2>Your feelings count, too.</h2><p className="section-intro">Living with changing symptoms or uncertainty can be tiring. PCOS is associated with a higher chance of anxiety and depression, and support is available.</p></div><div className="card"><div className="icon-tile"><Brain size={20} /></div><h3>Make space for support</h3><p>Tell someone you trust how you are doing. Bring mood changes to your next appointment and ask about counselling or other support. If you feel unsafe or might hurt yourself, contact local emergency services or a crisis service now.</p></div></div></section>

<section className="section section-alt" id="faq"><div className="container"><div className="eyebrow">06 · FAQs</div><h2>Good questions to keep close.</h2><div className="faq-list" style={{marginTop: "35px"}}><details><summary>Is PCOS caused by something I did?</summary><p>No. PCOS is a complex condition involving genes, hormones, and the environment. It is not a personal failure and is not caused by one food or habit.</p></details><details><summary>Can PCOS be cured?</summary><p>There is not currently a single cure, but symptoms and long-term health risks can often be managed. The right plan can change over time.</p></details><details><summary>Can I get pregnant with PCOS?</summary><p>Many people with PCOS become pregnant, with or without support. If you are trying to conceive, talk with a doctor about your options.</p></details><details><summary>Should I lose weight to manage PCOS?</summary><p>Health is not a number on a scale. Movement, nourishing food, sleep, and medical care can help people of all body sizes. Your care should never be based on shame.</p></details></div></div></section>

<section className="section" id="about"><div className="container split"><div><div className="eyebrow">About & sources</div><h2>Information you can trace.</h2></div><div><p className="section-intro">Cyclewise turns trusted guidance into plain-language summaries. Our reference point is the 2023 International Evidence-based Guideline for the Assessment and Management of PCOS, developed with healthcare professionals and people with lived experience.</p><a className="source" href="https://www.monash.edu/medicine/mchri/pcos/guideline" target="_blank" rel="noreferrer">View the full guideline at Monash University <ArrowUpRight size={13} /></a></div></div></section>

<div className="disclaimer"><div className="container"><p><strong>This website is for general information only, not medical advice.</strong> Please see a doctor for diagnosis or treatment. If you have urgent concerns, contact local emergency services.</p></div></div><footer className="footer"><div className="container footer-inner"><span>© 2026 cyclewise</span><span>Last updated {updated} · For education, with care.</span></div></footer></main>;
}
